# -*- coding: utf-8 -*-
"""account_logic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PrsE4eAxOzDbIqNgP8SmhSC_gh4j8uQs
"""

import numpy as np
import os
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')
data=[]
yourpath='/content/drive/My Drive/cloudaccount_logic'
allfilelist=os.listdir(yourpath)
alllist=os.walk(yourpath)
with open('data.txt', 'w') as f:
  for root, dirs, files in alllist:
    for filename in files:
        if filename.endswith('.txt'):
           file = open(os.path.join(root, filename), 'r')
           data=np.array(file.read())
           print(file.read())
           f.write(str(data))
           f.write('\n')



!cp data.txt /content/drive/MyDrive
fname = '/content/drive/My Drive/data.txt'
f = open(fname ,'r')
name_str = f.read()
print(str(name_str))
f.close()
from google.colab import files
files.download('data.txt')